### ISSUE TITLE
Modality specification in analysis functions

### ISSUE THREAD

**Issue by leo-desbureaux-tellae** [tellae/bhepop2#36]
When performing an analysis of the enrichment results (for instance using _analyse_enriched_populations_) , we provide a dict of modalities.

This is not consistent with the enrichment classes taking a list of attributes and inferring the modalities from the distributions.
In the other hand, this allows performing the analysis on a subset of modalities.

We should allow specifying a subset of modalities, but the complete set should be defined as in the enrichment classes.

This highlights some preprocessing duplication between enrichment and analysis. One way to avoid such duplication and ensure parameters consistency would be to call analysis from the enrichment class.

**Comment by PierreOlivierVandanjon** [comment]
But if  analyse_enriched_population is independent from the enrichment class, it can be used to analyze other solutions. For example, in our papers, we compare our solutions with solutions easier to compute in order to show the interest and the limit of the proposed methodology. To be discussed
